config/routes.rb
Rails.application.routes.draw do

  resources :modelos
  resources :tipos
  resources :relobps, only: [:index]

  resources :tipo_contratos
  resources :comodos
  resources :contas
  get 'contas_bancaria/update'

  resources :itens
  namespace :estoques do
    put 'data_vencimento/:id', to: "estoque_data_vencimento#update", as: :alter_data_vencimento
    put 'parcelamento/:id', to: "estoque_parcelamentos#update",as: :estoque_estoque_parcelamento
    put 'estoque-movimento/parcelamento/:id', to: "estoque_movimento_parcelas#update",as: :estoque_estoque_movimento_parcela
    get '/parcelas/resetar', to: "estoque_movimento_parcelas#reset",as: :reset_estoque_movimento_parcela
    post 'parcelamentos', to: "estoque_parcelamentos#find_and_create_portions",as: :estoque_estoque_parcelamento_find_and_create_portions
    get '/:estoque_movimentaco_id/desbloquear-valor', to: "estoque_movimento_parcelas#unlock_item", as: :unlock_estoque_movimento_parcela
    
    resources :estoque_movimentacoes do
      get 'parcelamentos', to: "estoque_parcelamentos#index"
      get 'buscar_parcelamentos', to: "estoque_parcelamentos#router", as: :router_parcelamento
      get 'editar_parcelamentos', to: "estoque_parcelamentos#editar_parcelamentos", as: :edit_parcelamentos
      get 'resetar-parcelas', to: "estoque_parcelamentos#reset_quotations", as: :reset_quotations
      post 'parcelas/reiniciar-valores', to: "estoque_movimento_parcelas#reload",as: :reload_estoque_movimento_parcela

      member do
        get 'lock_and_unlock_page'
        get 'unlock_through_validate_by'
      end

      resources :estoque_parcelamentos, except: [:index, :new, :create, :update] do
        member do
          put 'atualizar_parcelas'
          get 'unlock_value'
        end
      end
      resources :estoque_transferencias, except: [:show, :edit]
      resources :estoque_produtos, except: [:show, :edit]
    end
  end

  resources :itens_obra do
    member do
      get 'report_individual'
    end
  end
  resources :bancos
  resources :categorias
  resources :cliente_fornecedores, except: [:destroy]

  resources :obras do
    member do
      delete 'destroy_comodo'
    end
  end
  resources :produto_categorias
  resources :produtos
  resources :services

  # get 'itens_obras/', to: "itens_obra#index", as: :itens_obras
  # post 'sub_itens_obras/search', to: "itens_obra#search", as: :search_sub_itens_obras
  # post 'itens_obras/search', to: "itens_obra#search_itens", as: :search_itens_obras

  devise_for :users,
              patch: 'brant/users',
              controllers: { sessions: "brant/users/sessions" },
              path_names:  { sign_in: "signin", sign_out: "signout" },
              skip: [:registrations]
  as :user do
    get 'empresa/brant/users/sign-up', to: 'backstage/users/registrations#new', as: :new_user_registration
    get 'empresa/brant/users/edit/:id', to: 'backstage/users/registrations#edit', as: :edit_user_registration
    post 'empresa/brant/users/sign-up', to: 'backstage/users/registrations#create', as: :create_user_registration
    put 'empresa/brant/users/edit/:id/update', to: 'backstage/users/registrations#update', as: :update_user_registration
    delete 'empresa/brant/users/delete/:id', to: 'backstage/users/registrations#destroy', as: :destroy_user_registration
  end

  devise_for :admins,
              path: 'brant/admins',
              controllers: { sessions: "backstage/admin/sessions" },
              path_names:  { sign_in: "signin", sign_out: "signout" }


  namespace :backstage do
    resources :authorizations
    resources :dashboard, only: [:index]
    get 'user/:id/authorizations/', to: "users/permissions#index", as: :user_permissions
    post'user/:id/authorizations/', to: "users/permissions#update", as: :add_user_permissions
    get 'empresa/brant', to: "dashboard#brant"
    get 'empresa/brant/models', to: "dashboard#models"
    get 'empresa/brant/admins', to: "dashboard#admins"
    get 'empresa/brant/users', to: "dashboard#users"
  end

  authenticated :admin do
    root 'backstage/dashboard#index', as: :dashboard_root
  end

  devise_scope :user do
    unauthenticated do
      root "brant/home#index"
    end
  end

  namespace :brant do
    get 'home/index', as: :index_root
    namespace :users do
      resources :accounts
      resources :user_authorizations
    end
    resources :report_configurations

    get 'itens_obra/report_all', to: "reports#report_all_etapas", as: :report_all_item_obra
    get 'print_individual/cliente_fornecedores', to: "reports#print_individual_cliente_fornecedor", as: :print_individual_cliente_fornecedor
    get 'print_page/cliente_fornecedores', to: "reports#print_page_cliente_fornecedor", as: :print_page_cliente_fornecedor
  end

  get 'resquests/create_banco_through_ajax', to: "brant/requests#create_banco_through_ajax"
  get 'resquests/create_comodo_through_ajax', to: "brant/requests#create_comodo_through_ajax"
  get 'resquests/create_categoria_through_ajax', to: "brant/requests#create_categoria_through_ajax"
  get 'resquests/create_service_through_ajax', to: "brant/requests#create_service_through_ajax"
  get 'resquests/create_product_through_ajax', to: "brant/requests#create_product_through_ajax"
  get 'resquests/create_work_through_ajax', to: "brant/requests#create_work_through_ajax"
  get 'resquests/find_resource',                to: "brant/requests#find_resource"
  get 'resquests/collect_fornecedor_services', to: "brant/requests#collect_fornecedor_services"
  get 'resquests/collect_fornecedor_products', to: "brant/requests#collect_fornecedor_products"
  get 'resquests/collect_cliente_obras', to: "brant/requests#collect_cliente_obras"
  get 'resquests/find_client_obra_and_destroy', to: "brant/requests#destroy_cliente_obras"
  get 'resquests/find_fornecedor_service_and_destroy', to: "brant/requests#destroy_fornecedor_services"
  get 'resquests/find_fornecedor_product_and_destroy', to: "brant/requests#destroy_fornecedor_products"
  get 'resquests/collect_contas_bancarias', to: "brant/requests#collect_contas_bancarias"


  root "brant/home#index"
end

app/models/concerns/estoque/parcelamentos/pagamento_concern.rb
module Estoque::Parcelamentos::PagamentoConcern
    extend ActiveSupport::Concern

    included do
        module Periodo
            def Periodo.semanal()
                return 7
            end

            def Periodo.quinzenal()
                return 15
            end

            def Periodo.mensal()
                return 1
            end

            def Periodo.anual()
                return 1
            end
        end
    end
end

app/models/estoque.rb
module Estoque
  def self.table_name_prefix
    'estoque_'
  end
end

app/controllers/estoques/estoque_data_vencimento_controller.rb
#-*- coding: utf-8 -*-
class Estoques::EstoqueDataVencimentoController < EstoquesController
  def update
    @estoque_movimento_parcela = Estoque::EstoqueMovimentoParcela.find(params[:id])
    @estoque = @estoque_movimento_parcela.estoque_movimento
    @estoque_movimento_parcela.update_attributes(data_vencimento: params[:data_vencimento])

    if !@estoque.tipo_movimentacao.eql?("Transferência")
      @estoque_produtos = @estoque.estoque_produtos
      @estoque_produtos.each do |ep|
        ep.estoque_produto_parcelamentos.where(parcela: @estoque_movimento_parcela.parcela).each do |epp|
          epp.update_attributes(data_vencimento: params[:data_vencimento])
        end
      end
    else
      @estoque_transferencias = @estoque.estoque_transferencias
      @estoque_transferencias.each do |et|
        et.estoque_transferencia_parcelamentos.where(parcela: @estoque_movimento_parcela.parcela).each do |etp|
          etp.update_attributes(data_vencimento: params[:data_vencimento])
        end
      end
    end
  end
end

app/controllers/estoques/estoque_movimentacoes_controller.rb
#-*- coding: utf-8 -*-
class Estoques::EstoqueMovimentacoesController < EstoquesController
  include ParcelamentoConcern
  include FiltroEstoque

  before_action :find_estoque, only: [:show, :edit, :update, :unlock_through_validate_by]
  respond_to :html

  def index
    @status_validos = Estoque::EstoqueMovimento::STATUS_VALIDOS.map { |v| v.to_s }

    if params[:q]
      filtro_de_todos
      filtro_de_entrada
      filtro_de_devolucao
      filtro_de_transferencia_entrada
      filtro_de_transferencia_saida
    else
      @estoque_incompleto = Estoque::EstoqueMovimento.all
      @estoque_incompleto.each do |ei|
        if !ei.tipo_movimentacao.upcase.eql?("TRANSFERÊNCIA")
          ei.confronta_valores_de_produtos
        else
          ei.confronta_valores_de_transferencia
        end
      end
      @search = Estoque::EstoqueMovimento.ransack(params[:q])
      @estoques = @search.result(distinct: true).order_by_incompleto.page params[:page]
    end
  end

  def show
    session[:item_id] = nil
    if !@estoque.tipo_movimentacao.upcase.eql?("TRANSFERÊNCIA")
      @estoque_produtos = @estoque.estoque_produtos.page params[:page]
    else
      @estoque_transferencias = @estoque.estoque_transferencias.page params[:page]
    end
  end

  def new
    session[:item_id] = nil
    session[:qtParcelas]= nil 
    @estoque = user.estoques_movimentos.build
  end

  def edit
    session[:item_id] = nil
    session[:qtParcelas]= nil
    @estoque_movimento_parcelas = @estoque.estoque_movimento_parcelas
  end
  
  def create
    _start_
    if _successfully_created_
      session[:qtParcelas]= @estoque.parcelas
      _check_transfer_
      _create_parcelas_
    end
  end
  
  def update
    if _successfully_updated_
      _check_transfer_
      _create_parcelas_
      _reload_if_item_parcelas_
    end
  end

  def unlock_through_validate_by
    $total_produtos = @estoque.return_total_produtos if !@estoque.tipo_movimentacao.eql?("Transferência")
    $total_produtos = @estoque.return_total_produtos_transferencia if @estoque.tipo_movimentacao.eql?("Transferência")
    $total_estoque = 0
    if @estoque.valida_por.eql?("total_estoque")
      $total_estoque = @estoque.total_estoque.to_f
      if ($total_produtos < $total_estoque) or ($total_produtos > $total_estoque)
        $lock = true
      else
        $lock = false
      end
    elsif @estoque.valida_por.eql?("total_produtos")
      $total_estoque = @estoque.valor_total_produto.to_f
      if ($total_produtos < $total_estoque) or ($total_produtos > $total_estoque)
        $lock = true
      else
        $lock = false
      end
    end
    respond_to &:js
  end

  private
    def _start_
      @estoque = user.estoques_movimentos.build(resource_params)
    end

    def _successfully_created_
      @estoque.save
    end

    def _check_transfer_
      if @estoque.tipo_movimentacao.eql?("Transferência")
        @estoque.add_transferencia_tipo=resource_params[:transferencia_tipo]
        @estoque.save
      end
    end

    def _reload_if_item_parcelas_
      if !@estoque.tipo_movimentacao.eql?("Transferência")
        @estoque_produtos = @estoque.estoque_produtos
        unless @estoque_produtos.empty?
          @estoque_produtos.each do |ep|
            Estoque::EstoqueProduto.build_parcelamento_from_source(ep, @estoque.parcelas)
          end
        end
      else
        @estoque_transferencias = @estoque.estoque_transferencias
        unless @estoque_transferencias.empty?
          @estoque_transferencias.each do |et|
            Estoque::EstoqueTransferencia.build_parcelamento_from_source(et, @estoque.parcelas)
          end
        end
      end
    end

    def _successfully_updated_
      @estoque.update(resource_params)
      session[:qtParcelas]= @estoque.parcelas
    end

    def find_estoque
      @id = check_params
      @estoque = Estoque::EstoqueMovimento.find_by(id: @id.call(params[:id], params[:estoque_movimentaco_id]))
    end

    def resource_params
      params.require(:estoque_estoque_movimento).permit(:id,
                                                        :tipo_movimentacao,
                                                        :fornecedor_id,
                                                        :destinatario_tomador_id,
                                                        :user_id,
                                                        :nota_fiscal_entrada,
                                                        :numero_pedido,
                                                        :recibo,
                                                        :cupom_fiscal,
                                                        :numero_da_os,
                                                        :nota_fiscal_saida,
                                                        :data_entrada,
                                                        :data_vencimento_entrada,
                                                        :data_vencimento_saida,
                                                        :data_saida,
                                                        :data_devolucao,
                                                        :data_transferencia,
                                                        :justificativa_devolucao,
                                                        :transferencia_tipo,
                                                        :total_estoque,
                                                        :parcelas,
                                                        :periodo,
                                                        :valor_total_produto,
                                                        :acrescimo,
                                                        :boleto,
                                                        :frete,
                                                        :desconto,
                                                        :observacoes,
                                                        :valida_por,
                                                        :pronto_pagamento)
    end
end

app/controllers/estoques/estoque_produtos_controller.rb
# -*- coding: utf-8 -*-
class Estoques::EstoqueProdutosController < BrantController
  include CurrentItem
  before_action :find_estoque
  respond_to :html

  def new
    verifica_itens_adicionados
    @estoque_produto = @estoque.estoque_produtos.build
    @produto = @estoque.produtos.build
    @produto.categorias.build
    session[:qtParcelas]= @estoque.parcelas
  end

  def create
    if resource_params[:id].eql?("")
      verifica_itens_adicionados
      @estoque_produto = @item.add_produto_to_estoque(resource_params)
      @estoque_produto.verify_last_stock
      @estoque_produto.add_or_remove_through_stock_moviment
      if @estoque_produto.save
        @estoque_produto.save_product_at_provider_if_not_exists
        @estoque_produto_parcelamentos = Estoque::EstoqueProduto.build_parcelamento_from_source(@estoque_produto, session[:qtParcelas])
        if @estoque_produto_parcelamentos 
          flash[:notice]=t("flash.actions.#{__method__}.success", resource_name: "Produto")
          redirect_to new_estoques_estoque_movimentaco_estoque_produto_path(@estoque)
        end
      else
        flash[:error]=t("flash.actions.#{__method__}.alert", resource_name: "Produto")
        @item = Item.find(session[:item_id])
        render :new
      end
    else
      update
    end
  end

  def update
    @estoque_produto = @estoque.estoque_produtos.find(resource_params[:id])
    @estoque_produto.verify_changes_on_main_fields(resource_params)
    @estoque_produto.simula_valor_total_de_produtos(resource_params[:valor_produto])

    if @estoque_produto.save
      @estoque_produto_parcelamentos = Estoque::EstoqueProduto.build_parcelamento_from_source(@estoque_produto, session[:qtParcelas])
      if @estoque_produto_parcelamentos
        flash[:notice] = t("flash.actions.#{__method__}.success", resource_name: "Produto")
        redirect_to new_estoques_estoque_movimentaco_estoque_produto_path(@estoque)
      end
    else
      flash[:error] = t("flash.actions.#{__method__}.alert", resource_name: "Produto")
      render 'new'
    end
  end

  def destroy
    @estoque_produto = Estoque::EstoqueProduto.find(params[:id])
    @estoque = Estoque::EstoqueMovimento.find(params[:estoque_movimentaco_id])
    @deleted_id =@estoque_produto.id
    
    if @estoque_produto.destroy
      @confirmed = true
    else
      @confirmed = false
    end
  end


  private
    def verifica_itens_adicionados
      @estoque_produto = @estoque.estoque_produtos.last
      if !@estoque_produto.nil?
        @item = @estoque_produto.item
        session[:item_id] = @item.id
      elsif session[:item_id] != nil
        @item = Item.find(session[:item_id])
      else
        @item = Item.create
        session[:item_id] = @item.id
      end
    end

    def find_estoque
      @estoque = Estoque::EstoqueMovimento.find(params[:estoque_movimentaco_id])
    end

    def resource_params
      params.require(:estoque_estoque_produto).permit(:id,
                                                      :produto_id,
                                                      :estoque_movimento_id,
                                                      :obra_id,
                                                      :comodo_id,
                                                      :item_obra_id,
                                                      :sub_item_obra_id,
                                                      :quantidade_movimento,
                                                      :quantidade_anterior,
                                                      :quantidade_atual,
                                                      :valor_produto,
                                                      :valor_total,
                                                      :observacoes)
    end
end

app/views/estoques/estoque_produtos/_btns_form_section.html.haml
.pull-left
  = button_tag(type: "submit", id: "btn_save_estoque_produto", class: 'btn btn-primary', title: "Adicionar Produto no Estoque", style: "margin-top: 23px;") do
    %i.fa.fa-plus{"aria-hidden" => "true"}
    =t('helpers.links.add')
  =content_tag :div, id: "btn_estoque_produto_edit", style: "display: none" do
    = button_tag(type: "submit", id: "btn_edit_estoque_produto", class: 'btn btn-warning', title: "Atualizar Produto no Estoque", style: "margin-top: 23px;") do
      %i.fa.fa-edit{"aria-hidden" => "true"}
      =t('helpers.links.edit')
.pull-right
  =link_to unlock_through_validate_by_estoques_estoque_movimentaco_path(@estoque), class: 'btn btn-default', remote: true, style: "margin-top: 23px;", data: { valida_por: @estoque.valida_por, valor_total: @estoque.total_estoque.to_s, total_produtos: @estoque.valor_total_produto.to_s} do
    %i.fa.fa-archive{"aria-hidden" => "true"}
    =t('helpers.links.finish_release')

app/views/estoques/estoque_produtos/_categoria_fields.html.haml
.panel.panel-default
  .panel-heading
    .row
      %h4.center
        %b=t('helpers.titles.new_categoria')
    .row
      .col-xs-12.col-sm-8.col-md-2.col-lg-12
        =f.input :nome, input_html: {id: "categoria_nome"}
    .row
      .col-xs-12.col-sm-12.col-md-12.col-lg-12
        .btn-group.pull-right
          = link_to "#", class: 'btn btn-default', title: "Salvar Produto", id: "btn_salvar_categoria" do
            %i.fa.fa-check{"aria-hidden" => "true"}
          = link_to "#", class: 'btn btn-warning', title: "Cancelar", id: "btn_cancelar_categoria" do
            %i.fa.fa-times{"aria-hidden" => "true"}

app/views/estoques/estoque_produtos/_estoque_produto_fields.html.haml
.row
  =f.input :estoque_movimento_id, as: :hidden, input_html: { value: @estoque.id }
  =f.input :id, as: :hidden
.row
  .col-xs-12.col-sm-8.col-md-4.col-lg-4
    =label_error_tag f,:produto, @estoque_produto, :produto_id
    .produto_data_live_search
      .input-group
        =f.collection_select(:produto_id, Produto.order(nome: :asc), :id, :descricao, {:prompt=>true}, {class: "form-control tab data_live_search", :"data-live-search"=> true})
        %span.input-group-btn
          %button{ class: "btn btn-default docs-datepicker-trigger", style: "margin-top: 0 !important", disabled: false, id: "btn_new_product_on_estoque_form"}
            %i{ class: "fa fa-plus", :"aria-hidden"=>"true"}
    =error_tag @estoque_produto, :produto_id
.row
  .col-xs-12.col-sm-8.col-md-4.col-lg-4
    .estoque_obra_data_live_search
      =label_error_tag f,:obra, @estoque_produto, :obra_id
      =f.collection_select(:obra_id, Obra.where.not(codigo: "BRANT").order(codigo: :asc), :id, :codigo, {:prompt=>true}, {class: "form-control tab data_live_search", :"data-live-search"=> true})
    =error_tag @estoque_produto, :obra_id
  .col-xs-12.col-sm-8.col-md-5.col-lg-5{style: "margin-left: 9%"}
    =label_error_tag f,"Cômodo", @estoque_produto, :comodo_id
    =f.grouped_collection_select(:comodo_id, Obra.where.not(codigo: "BRANT").order(codigo: :asc), :comodo_obras, :codigo, :id , :comodo_name, {:prompt=>"Por Favor Selecione"}, {class: "form-control data_live_search", :"data-live-search"=> true})
.row
  .col-xs-12.col-sm-8.col-md-5.col-lg-5
    .estoque_data_live_search
      =label_error_tag f,t("helpers.labels.etapa"), @estoque_produto, :item_obra_id
      =f.collection_select(:item_obra_id, ItemObra.order(item: :asc), :id, :item_obra_descricao, {:prompt=>true}, {class: "data_live_search", :"data-live-search"=> true})
    =error_tag @estoque_produto, :item_obra_id
  .col-xs-12.col-sm-8.col-md-5.col-lg-5
    =label_error_tag f,t("helpers.labels.sub_etapa"), @estoque_produto, :sub_item_obra_id
    =f.grouped_collection_select(:sub_item_obra_id, ItemObra.order(item: :asc), :sub_itens_obras, :item_obra_descricao, :id, :sub_item_obra_descricao, {:prompt=>true}, {class: "form-control data_live_search", :"data-live-search"=> true})
    =error_tag @estoque_produto, :sub_item_obra_id
.row
  .col-xs-12.col-sm-8.col-md-5.col-lg-5
    =f.input :quantidade_movimento, label: t("helpers.labels.quantidade"), input_html: {min: 1}
  .col-xs-12.col-sm-8.col-md-5.col-lg-5
    =f.input :valor_produto, label: t("helpers.labels.valor"), input_html: { class: "campo_dinheiro" }, as: :string
.row
  .col-xs-12.col-sm-8.col-md-5.col-lg-5
    =f.input :valor_total, label: "Valor Total do Produto", input_html: { class: "campo_dinheiro", value: @estoque_produto.valor_total.to_money.to_s }, as: :string, readonly: true
.row
  .col-xs-12.col-sm-12.col-md-10.col-lg-10
    =f.input :observacoes, as: :text, label: "Observações"

app/views/estoques/estoque_produtos/_form.html.haml
=simple_form_for [@estoque, @estoque_produto], url: estoques_estoque_movimentaco_estoque_produtos_path, method: "POST" do |f|
  %br/
  .row
    .col-xs-12.col-sm-8.col-md-5.col-lg-5
      =render 'estoque_produto_fields', {f: f}
    .col-xs-12.col-sm-8.col-md-7.col-lg-7
      #estoque_produto_fields{style: "display: none"}
        .panel
          = f.simple_fields_for :produtos do |produto|
            =render 'produto_fields', {f: produto }
      #estoque_itens_armazenados
        .panel.panel-default
          .panel-heading
            %h3.center
              %strong Estoque Itens
            %hr
            -if !@item.estoque_produtos.empty?
              =render 'itens/item'
          .panel-bottom
            -if !@item.estoque_produtos.empty?
              %div{style: "margin-top: 10px"}
                .container-fluid
                  #total_estoque
                    =render 'estoques/estoque/estoque_produtos/total_produtos', {source: @item.estoque_produtos}
  .row-fluid{style: "margin-bottom: 5%"}
    =render 'btns_form_section', {f: f}

app/views/estoques/estoque_produtos/_produtos.html.haml
- totalProdutos = 0
- if @estoque_produtos
  - @estoque_produtos.each do |estoque_produto|
    - totalProdutos += estoque_produto.valor_total

.container
  .well
    %h4
      %b=t('helpers.labels.produtos_added')
    .pull-right
      - if @estoque.tipo_movimentacao.eql?("Entrada") || @estoque.tipo_movimentacao.eql?("Devolução para Fornecedor")
        -if totalProdutos < @estoque.total_estoque
          =link_to new_estoques_estoque_movimentaco_estoque_produto_url(@estoque), class: "btn btn-danger" do
            %i.fa.fa-plus
            =t('helpers.links.add_produto')
      -if @estoque.tipo_movimentacao.eql?("Transferencia")
        =link_to new_estoques_estoque_movimentaco_estoque_transferencia_path(@estoque), id: "add_item_produto", class: "btn btn-danger" do
          %i.fa.fa-plus
          =t('helpers.links.add_produto')
    .page-header
    %table.table.table-condensed.table-hover.table-striped
      %caption
        %b=t('helpers.labels.total_produtos', total: "#{@estoque.estoque_produtos.count}")
      %thead
        %tr
          %th=t('produtos.helpers.nome')
          %th.center=t('helpers.labels.obra')
          %th.center=t('helpers.labels.etapa')
          %th.center=t('helpers.labels.sub_etapa')
          %th.center=t('produtos.helpers.quantidade')
          %th.center=t('produtos.helpers.valor')
          %th
            .pull-right=t('produtos.helpers.valor_total')
          %th
          %th
      %tbody.estoque_produto
        =render @estoque_produtos
      %caption{style: "caption-side: bottom;"}
        .pull-left
          %b=t('pages.helpers.labels.total_estoque_produtos')
        .pull-right
          #total_estoque
            %strong.badge{style: "background: #000000; color: #FFFE00"}=total_produtos(@estoque_produtos)
    #estoque_produto_paginator
      =paginate @estoque_produtos, remote: true

app/views/estoques/estoque_produtos/destroy.js.erb
<%- if @confirmed == true -%>
  $("#tr_estoque_produto_id_<%= @deleted_id %>").remove()
  $("#total_estoque").fadeOut(500)
  $("#total_estoque").fadeIn(500).html("<%=j render 'estoques/estoque/estoque_produtos/total_produtos', {source: @estoque.estoque_produtos} %>")
  $("#add_item_produto").fadeOut(500).fadeIn(500)
  $.message({ title: 'Aviso!', content: "<%= t('flash.actions.destroy.success', resource_name: 'Produto')%>", position: "topright", color: "yellow" })
<%- else -%>
  $.message({ title: 'Aviso!', content: "<%= t('flash.actions.destroy.alert', resource_name: 'Produto')%>", position: "topright", color: "red" })
<%- end -%>

app/views/estoques/estoque_produtos/new.html.haml
%section{id: "estoque_dados_movimento"}
  .container-fluid
    .row-fluid
      %span.breadcrumb-item.active Você está em
      %h4.page_header{style: "border-bottom: #AEAEAE 0.5px solid"}
        .pull-right
          = link_to edit_estoques_estoque_movimentaco_path(@estoque), class: 'btn btn-primary' do
            %i.fa.fa-edit{"aria-hidden" => "true"}
            =t('helpers.links.change_data_moviment')
        %ol.arrows
          %li
            %a{:href => "#"}="Estoque Nº #{@estoque.id}"
          %li
            %a{:href => "#"}="Adicionar Produtos"
  .container-fluid
    .panel.panel-default
      .panel-heading
        #exTab3.container-fluid
          %ul.nav.nav-pills
            %li
              %a{"data-toggle" => "tab", :href => "#tab_moviment"}=t('estoques.links.tab_moviment')
            %li.active
              %a{"data-toggle" => "tab", :href => "#tab_product"}=t('estoques.links.tab_product')
      .panel-body
        .tab-content.clearfix
          #tab_moviment.tab-pane.fade.in
            =render 'estoques/estoque_movimentacoes/estoque/movimento'
          #tab_product.tab-pane.fade.in.active
            =render 'form'

%section#warning_modal
  =render 'estoques/componentes/page_lock'

= javascript_include_tag "https://code.jquery.com/jquery-3.2.1.js"
= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.0/moment.min.js"
= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.0/moment-with-locales.min.js"
= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.0/locale/pt-br.js"

= javascript_include_tag "brant/estoques/produto"
= javascript_include_tag "brant/estoques/produto_etapas_da_obra"
= javascript_include_tag "brant/estoques/obra_comodo_group_collection"
=javascript_include_tag "brant/estoques/estoque_produto", cache: true