config/routes.rb
Rails.application.routes.draw do

  resources :modelos
  resources :tipos
  resources :relobps, only: [:index]

  resources :tipo_contratos
  resources :comodos
  resources :contas
  get 'contas_bancaria/update'

  resources :itens
  namespace :estoques do
    put 'data_vencimento/:id', to: "estoque_data_vencimento#update", as: :alter_data_vencimento
    put 'parcelamento/:id', to: "estoque_parcelamentos#update",as: :estoque_estoque_parcelamento
    put 'estoque-movimento/parcelamento/:id', to: "estoque_movimento_parcelas#update",as: :estoque_estoque_movimento_parcela
    get '/parcelas/resetar', to: "estoque_movimento_parcelas#reset",as: :reset_estoque_movimento_parcela
    post 'parcelamentos', to: "estoque_parcelamentos#find_and_create_portions",as: :estoque_estoque_parcelamento_find_and_create_portions
    get '/:estoque_movimentaco_id/desbloquear-valor', to: "estoque_movimento_parcelas#unlock_item", as: :unlock_estoque_movimento_parcela
    
    resources :estoque_movimentacoes do
      get 'parcelamentos', to: "estoque_parcelamentos#index"
      get 'buscar_parcelamentos', to: "estoque_parcelamentos#router", as: :router_parcelamento
      get 'editar_parcelamentos', to: "estoque_parcelamentos#editar_parcelamentos", as: :edit_parcelamentos
      get 'resetar-parcelas', to: "estoque_parcelamentos#reset_quotations", as: :reset_quotations
      post 'parcelas/reiniciar-valores', to: "estoque_movimento_parcelas#reload",as: :reload_estoque_movimento_parcela

      member do
        get 'lock_and_unlock_page'
        get 'unlock_through_validate_by'
      end

      resources :estoque_parcelamentos, except: [:index, :new, :create, :update] do
        member do
          put 'atualizar_parcelas'
          get 'unlock_value'
        end
      end
      resources :estoque_transferencias, except: [:show, :edit]
      resources :estoque_produtos, except: [:show, :edit]
    end
  end

  resources :itens_obra do
    member do
      get 'report_individual'
    end
  end
  resources :bancos
  resources :categorias
  resources :cliente_fornecedores, except: [:destroy]

  resources :obras do
    member do
      delete 'destroy_comodo'
    end
  end
  resources :produto_categorias
  resources :produtos
  resources :services

  # get 'itens_obras/', to: "itens_obra#index", as: :itens_obras
  # post 'sub_itens_obras/search', to: "itens_obra#search", as: :search_sub_itens_obras
  # post 'itens_obras/search', to: "itens_obra#search_itens", as: :search_itens_obras

  devise_for :users,
              patch: 'brant/users',
              controllers: { sessions: "brant/users/sessions" },
              path_names:  { sign_in: "signin", sign_out: "signout" },
              skip: [:registrations]
  as :user do
    get 'empresa/brant/users/sign-up', to: 'backstage/users/registrations#new', as: :new_user_registration
    get 'empresa/brant/users/edit/:id', to: 'backstage/users/registrations#edit', as: :edit_user_registration
    post 'empresa/brant/users/sign-up', to: 'backstage/users/registrations#create', as: :create_user_registration
    put 'empresa/brant/users/edit/:id/update', to: 'backstage/users/registrations#update', as: :update_user_registration
    delete 'empresa/brant/users/delete/:id', to: 'backstage/users/registrations#destroy', as: :destroy_user_registration
  end

  devise_for :admins,
              path: 'brant/admins',
              controllers: { sessions: "backstage/admin/sessions" },
              path_names:  { sign_in: "signin", sign_out: "signout" }


  namespace :backstage do
    resources :authorizations
    resources :dashboard, only: [:index]
    get 'user/:id/authorizations/', to: "users/permissions#index", as: :user_permissions
    post'user/:id/authorizations/', to: "users/permissions#update", as: :add_user_permissions
    get 'empresa/brant', to: "dashboard#brant"
    get 'empresa/brant/models', to: "dashboard#models"
    get 'empresa/brant/admins', to: "dashboard#admins"
    get 'empresa/brant/users', to: "dashboard#users"
  end

  authenticated :admin do
    root 'backstage/dashboard#index', as: :dashboard_root
  end

  devise_scope :user do
    unauthenticated do
      root "brant/home#index"
    end
  end

  namespace :brant do
    get 'home/index', as: :index_root
    namespace :users do
      resources :accounts
      resources :user_authorizations
    end
    resources :report_configurations

    get 'itens_obra/report_all', to: "reports#report_all_etapas", as: :report_all_item_obra
    get 'print_individual/cliente_fornecedores', to: "reports#print_individual_cliente_fornecedor", as: :print_individual_cliente_fornecedor
    get 'print_page/cliente_fornecedores', to: "reports#print_page_cliente_fornecedor", as: :print_page_cliente_fornecedor
  end

  get 'resquests/create_banco_through_ajax', to: "brant/requests#create_banco_through_ajax"
  get 'resquests/create_comodo_through_ajax', to: "brant/requests#create_comodo_through_ajax"
  get 'resquests/create_categoria_through_ajax', to: "brant/requests#create_categoria_through_ajax"
  get 'resquests/create_service_through_ajax', to: "brant/requests#create_service_through_ajax"
  get 'resquests/create_product_through_ajax', to: "brant/requests#create_product_through_ajax"
  get 'resquests/create_work_through_ajax', to: "brant/requests#create_work_through_ajax"
  get 'resquests/find_resource',                to: "brant/requests#find_resource"
  get 'resquests/collect_fornecedor_services', to: "brant/requests#collect_fornecedor_services"
  get 'resquests/collect_fornecedor_products', to: "brant/requests#collect_fornecedor_products"
  get 'resquests/collect_cliente_obras', to: "brant/requests#collect_cliente_obras"
  get 'resquests/find_client_obra_and_destroy', to: "brant/requests#destroy_cliente_obras"
  get 'resquests/find_fornecedor_service_and_destroy', to: "brant/requests#destroy_fornecedor_services"
  get 'resquests/find_fornecedor_product_and_destroy', to: "brant/requests#destroy_fornecedor_products"
  get 'resquests/collect_contas_bancarias', to: "brant/requests#collect_contas_bancarias"


  root "brant/home#index"
end

app/models/comodo.rb
# == Schema Information
#
# Table name: comodos
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

#-*- coding: utf-8 -*-
class Comodo < ApplicationRecord
  has_many :comodo_obras
  has_many :obras, through: :comodo_obras

  validates_presence_of :name

  before_create :upcase_name_before_create

  paginates_per 20

  def self.search(source)
    where('name LIKE ?', "%#{source[:name]}%").
    order(id: :desc).distinct
  end

  def upcase_name_before_create
    name.upcase!
  end
end

app/controllers/comodos_controller.rb
class ComodosController < BrantController
  before_action :set_comodo, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    if params[:q]
      @search = Comodo.search(params[:q])
      @comodos = @search.page(params[:page])
    else
      @comodos = Comodo.all.order(name: :asc).page(params[:page])
    end
  end

  def show
    respond_with(@comodo)
  end

  def new
    @comodo = Comodo.new
    respond_with(@comodo)
  end

  def edit
  end

  def create
    @comodo = Comodo.new(comodo_params)
    unless @comodo.save
      render :new
    else
      flash[:notice] = t("flash.actions.#{__method__}.notice", resource_name: @comodo.name) 
      redirect_to :back
    end
  end

  def update
    unless @comodo.update(comodo_params)
      render :edit
    else
      flash[:notice] = t("flash.actions.#{__method__}.success", resource_name: @comodo.name) 
      redirect_to comodos_path
    end
  end

  def destroy
    @comodo.destroy
  end

  private
    def set_comodo
      @comodo = Comodo.find(params[:id])
    end

    def comodo_params
      params.require(:comodo).permit(:name)
    end
end

app/views/comodos/_comodo.html.haml
%tr{id: "tr_comodo_id_#{comodo.id}"}
  %td= comodo.name
  %td 
    .btn-group.pull-right
      -# = link_to comodo, class: "btn btn-default btn-circle" do
      -#   %i.fa.fa-newspaper-o{style: "font-size: 14pt; margin-left: 3px"}
      =link_to edit_comodo_path(comodo), class: "btn btn-primary btn-circle", target: :_blank do
        %i.fa.fa-edit{style: "font-size: 14pt; margin-left: 3px"}
      =link_to comodo, method: :delete, data: { confirm: t('helpers.links.confirm_delete') }, remote: true, class: "btn btn-danger btn-circle" do
        %i.fa.fa-trash{style: "font-size: 14pt; margin-left: 3px"}

app/views/comodos/_condition_fields.html.haml
%div{class: "row", style:"margin-bottom: 1%;"}
  %div{class: "field"}
    %div{class: "col-xs-12 col-sm-3 col-md-3 col-lg-3 input_filtro"}
      = f.text_field :name

app/views/comodos/_form.html.haml
= simple_form_for(@comodo) do |f|
  = f.error_notification
  .row
    .col-md-4
      = f.input :name, label: t('helpers.labels.name')
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12
      .form-actions
        .pull-left
          = button_tag(type: "submit", class: "btn btn-success") do
            %i.fa.fa-check{"aria-hidden" => "true"}
            =t('helpers.links.save')
        .pull-right
          = link_to comodos_path, class: 'btn btn-danger', data: { confirm: "Tem Certeza?" }, method: :get do
            %i.fa.fa-times{"aria-hidden" => "true"}
            =t('helpers.links.cancel')

app/views/comodos/destroy.js.erb
$("#tr_comodo_id_<%= @comodo.id %>").fadeOut("fast")

app/views/comodos/edit.html.haml
%section{id: "edit_comodo"}
  .container
    .row
      %h1.page-header{style: "border-bottom: #AEAEAE 0.5px solid"}
        =t('helpers.titles.edit', model: "Cômodo")
        = link_to comodos_path, class: 'btn btn-default pull-right' do
          %i.fa.fa-chevron-circle-left{"aria-hidden" => "true"}
          =t('helpers.links.back')
    .row
      .well
        = render 'form'

app/views/comodos/index.html.haml
.container
  .row
    %h1.page_header{style: "border-bottom: #AEAEAE 0.5px solid"}
      = t('helpers.titles.index', model: "Cômodos")
      - if can? :create, Comodo
        = link_to new_comodo_path, class: 'btn btn-primary btn-circle pull-right', title: t('helpers.links.new') do
          %i.fa.fa-plus{"aria-hidden" => "true"}
  .row
    .well
      = form_for :q, url: comodos_path, method: "GET", remote: true do |f|
        .row
          .col-md-4
            =label_tag t('helpers.labels.name')
            = f.text_field :"name", class: "form-control"
        .row-fluid
          .btn-group
            = button_tag(type: "submit", class: "btn btn-primary", style: "margin-top: 5px") do
              %i.fa.fa-search{"aria-hidden" => "true"}
              =t('helpers.links.search')
            = link_to comodos_path, remote: true, class: "btn btn-default", style: "margin-top: 5px" do
              %i.fa.fa-refresh
              =t('helpers.links.reload')
  .row
    .well
      .pull-right
        #paginator_4_comodos
          =paginate @comodos
      %table.table.table-bordered.table-hover.table-condensed
        %thead
          %tr
            %th=t('helpers.labels.name')
            %th
        %tbody#comodos_table_content
          =render @comodos

app/views/comodos/index.js.erb
$("#comodos_table_content").fadeIn(500).html("<%=j render @comodos %>")

app/views/comodos/new.html.haml
%section{id: "new_comodo"}
  .container
    .row
      %h1.page-header{style: "border-bottom: #AEAEAE 0.5px solid"}
        =t('helpers.titles.new', model: "Cômodo")
        = link_to comodos_path, class: 'btn btn-default pull-right' do
          %i.fa.fa-chevron-circle-left{"aria-hidden" => "true"}
          =t('helpers.links.back')
    .row
      .well
        = render 'form'

app/views/comodos/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @comodo.name

= link_to 'Edit', edit_comodo_path(@comodo)
\|
= link_to 'Back', comodos_path