config/routes.rb
Rails.application.routes.draw do

  resources :modelos
  resources :tipos
  resources :relobps, only: [:index]

  resources :tipo_contratos
  resources :comodos
  resources :contas
  get 'contas_bancaria/update'

  resources :itens
  namespace :estoques do
    put 'data_vencimento/:id', to: "estoque_data_vencimento#update", as: :alter_data_vencimento
    put 'parcelamento/:id', to: "estoque_parcelamentos#update",as: :estoque_estoque_parcelamento
    put 'estoque-movimento/parcelamento/:id', to: "estoque_movimento_parcelas#update",as: :estoque_estoque_movimento_parcela
    get '/parcelas/resetar', to: "estoque_movimento_parcelas#reset",as: :reset_estoque_movimento_parcela
    post 'parcelamentos', to: "estoque_parcelamentos#find_and_create_portions",as: :estoque_estoque_parcelamento_find_and_create_portions
    get '/:estoque_movimentaco_id/desbloquear-valor', to: "estoque_movimento_parcelas#unlock_item", as: :unlock_estoque_movimento_parcela
    
    resources :estoque_movimentacoes do
      get 'parcelamentos', to: "estoque_parcelamentos#index"
      get 'buscar_parcelamentos', to: "estoque_parcelamentos#router", as: :router_parcelamento
      get 'editar_parcelamentos', to: "estoque_parcelamentos#editar_parcelamentos", as: :edit_parcelamentos
      get 'resetar-parcelas', to: "estoque_parcelamentos#reset_quotations", as: :reset_quotations
      post 'parcelas/reiniciar-valores', to: "estoque_movimento_parcelas#reload",as: :reload_estoque_movimento_parcela

      member do
        get 'lock_and_unlock_page'
        get 'unlock_through_validate_by'
      end

      resources :estoque_parcelamentos, except: [:index, :new, :create, :update] do
        member do
          put 'atualizar_parcelas'
          get 'unlock_value'
        end
      end
      resources :estoque_transferencias, except: [:show, :edit]
      resources :estoque_produtos, except: [:show, :edit]
    end
  end

  resources :itens_obra do
    member do
      get 'report_individual'
    end
  end
  resources :bancos
  resources :categorias
  resources :cliente_fornecedores, except: [:destroy]

  resources :obras do
    member do
      delete 'destroy_comodo'
    end
  end
  resources :produto_categorias
  resources :produtos
  resources :services

  # get 'itens_obras/', to: "itens_obra#index", as: :itens_obras
  # post 'sub_itens_obras/search', to: "itens_obra#search", as: :search_sub_itens_obras
  # post 'itens_obras/search', to: "itens_obra#search_itens", as: :search_itens_obras

  devise_for :users,
              patch: 'brant/users',
              controllers: { sessions: "brant/users/sessions" },
              path_names:  { sign_in: "signin", sign_out: "signout" },
              skip: [:registrations]
  as :user do
    get 'empresa/brant/users/sign-up', to: 'backstage/users/registrations#new', as: :new_user_registration
    get 'empresa/brant/users/edit/:id', to: 'backstage/users/registrations#edit', as: :edit_user_registration
    post 'empresa/brant/users/sign-up', to: 'backstage/users/registrations#create', as: :create_user_registration
    put 'empresa/brant/users/edit/:id/update', to: 'backstage/users/registrations#update', as: :update_user_registration
    delete 'empresa/brant/users/delete/:id', to: 'backstage/users/registrations#destroy', as: :destroy_user_registration
  end

  devise_for :admins,
              path: 'brant/admins',
              controllers: { sessions: "backstage/admin/sessions" },
              path_names:  { sign_in: "signin", sign_out: "signout" }


  namespace :backstage do
    resources :authorizations
    resources :dashboard, only: [:index]
    get 'user/:id/authorizations/', to: "users/permissions#index", as: :user_permissions
    post'user/:id/authorizations/', to: "users/permissions#update", as: :add_user_permissions
    get 'empresa/brant', to: "dashboard#brant"
    get 'empresa/brant/models', to: "dashboard#models"
    get 'empresa/brant/admins', to: "dashboard#admins"
    get 'empresa/brant/users', to: "dashboard#users"
  end

  authenticated :admin do
    root 'backstage/dashboard#index', as: :dashboard_root
  end

  devise_scope :user do
    unauthenticated do
      root "brant/home#index"
    end
  end

  namespace :brant do
    get 'home/index', as: :index_root
    namespace :users do
      resources :accounts
      resources :user_authorizations
    end
    resources :report_configurations

    get 'itens_obra/report_all', to: "reports#report_all_etapas", as: :report_all_item_obra
    get 'print_individual/cliente_fornecedores', to: "reports#print_individual_cliente_fornecedor", as: :print_individual_cliente_fornecedor
    get 'print_page/cliente_fornecedores', to: "reports#print_page_cliente_fornecedor", as: :print_page_cliente_fornecedor
  end

  get 'resquests/create_banco_through_ajax', to: "brant/requests#create_banco_through_ajax"
  get 'resquests/create_comodo_through_ajax', to: "brant/requests#create_comodo_through_ajax"
  get 'resquests/create_categoria_through_ajax', to: "brant/requests#create_categoria_through_ajax"
  get 'resquests/create_service_through_ajax', to: "brant/requests#create_service_through_ajax"
  get 'resquests/create_product_through_ajax', to: "brant/requests#create_product_through_ajax"
  get 'resquests/create_work_through_ajax', to: "brant/requests#create_work_through_ajax"
  get 'resquests/find_resource',                to: "brant/requests#find_resource"
  get 'resquests/collect_fornecedor_services', to: "brant/requests#collect_fornecedor_services"
  get 'resquests/collect_fornecedor_products', to: "brant/requests#collect_fornecedor_products"
  get 'resquests/collect_cliente_obras', to: "brant/requests#collect_cliente_obras"
  get 'resquests/find_client_obra_and_destroy', to: "brant/requests#destroy_cliente_obras"
  get 'resquests/find_fornecedor_service_and_destroy', to: "brant/requests#destroy_fornecedor_services"
  get 'resquests/find_fornecedor_product_and_destroy', to: "brant/requests#destroy_fornecedor_products"
  get 'resquests/collect_contas_bancarias', to: "brant/requests#collect_contas_bancarias"


  root "brant/home#index"
end

app/models/concerns/estoque/parcelamentos/pagamento_concern.rb
module Estoque::Parcelamentos::PagamentoConcern
    extend ActiveSupport::Concern

    included do
        module Periodo
            def Periodo.semanal()
                return 7
            end

            def Periodo.quinzenal()
                return 15
            end

            def Periodo.mensal()
                return 1
            end

            def Periodo.anual()
                return 1
            end
        end
    end
end

app/models/estoque.rb
module Estoque
  def self.table_name_prefix
    'estoque_'
  end
end

app/controllers/estoques/estoque_data_vencimento_controller.rb
#-*- coding: utf-8 -*-
class Estoques::EstoqueDataVencimentoController < EstoquesController
  def update
    @estoque_movimento_parcela = Estoque::EstoqueMovimentoParcela.find(params[:id])
    @estoque = @estoque_movimento_parcela.estoque_movimento
    @estoque_movimento_parcela.update_attributes(data_vencimento: params[:data_vencimento])

    if !@estoque.tipo_movimentacao.eql?("Transferência")
      @estoque_produtos = @estoque.estoque_produtos
      @estoque_produtos.each do |ep|
        ep.estoque_produto_parcelamentos.where(parcela: @estoque_movimento_parcela.parcela).each do |epp|
          epp.update_attributes(data_vencimento: params[:data_vencimento])
        end
      end
    else
      @estoque_transferencias = @estoque.estoque_transferencias
      @estoque_transferencias.each do |et|
        et.estoque_transferencia_parcelamentos.where(parcela: @estoque_movimento_parcela.parcela).each do |etp|
          etp.update_attributes(data_vencimento: params[:data_vencimento])
        end
      end
    end
  end
end

app/controllers/estoques/estoque_movimentacoes_controller.rb
#-*- coding: utf-8 -*-
class Estoques::EstoqueMovimentacoesController < EstoquesController
  include ParcelamentoConcern
  include FiltroEstoque

  before_action :find_estoque, only: [:show, :edit, :update, :unlock_through_validate_by]
  respond_to :html

  def index
    @status_validos = Estoque::EstoqueMovimento::STATUS_VALIDOS.map { |v| v.to_s }

    if params[:q]
      filtro_de_todos
      filtro_de_entrada
      filtro_de_devolucao
      filtro_de_transferencia_entrada
      filtro_de_transferencia_saida
    else
      @estoque_incompleto = Estoque::EstoqueMovimento.all
      @estoque_incompleto.each do |ei|
        if !ei.tipo_movimentacao.upcase.eql?("TRANSFERÊNCIA")
          ei.confronta_valores_de_produtos
        else
          ei.confronta_valores_de_transferencia
        end
      end
      @search = Estoque::EstoqueMovimento.ransack(params[:q])
      @estoques = @search.result(distinct: true).order_by_incompleto.page params[:page]
    end
  end

  def show
    session[:item_id] = nil
    if !@estoque.tipo_movimentacao.upcase.eql?("TRANSFERÊNCIA")
      @estoque_produtos = @estoque.estoque_produtos.page params[:page]
    else
      @estoque_transferencias = @estoque.estoque_transferencias.page params[:page]
    end
  end

  def new
    session[:item_id] = nil
    session[:qtParcelas]= nil 
    @estoque = user.estoques_movimentos.build
  end

  def edit
    session[:item_id] = nil
    session[:qtParcelas]= nil
    @estoque_movimento_parcelas = @estoque.estoque_movimento_parcelas
  end
  
  def create
    _start_
    if _successfully_created_
      session[:qtParcelas]= @estoque.parcelas
      _check_transfer_
      _create_parcelas_
    end
  end
  
  def update
    if _successfully_updated_
      _check_transfer_
      _create_parcelas_
      _reload_if_item_parcelas_
    end
  end

  def unlock_through_validate_by
    $total_produtos = @estoque.return_total_produtos if !@estoque.tipo_movimentacao.eql?("Transferência")
    $total_produtos = @estoque.return_total_produtos_transferencia if @estoque.tipo_movimentacao.eql?("Transferência")
    $total_estoque = 0
    if @estoque.valida_por.eql?("total_estoque")
      $total_estoque = @estoque.total_estoque.to_f
      if ($total_produtos < $total_estoque) or ($total_produtos > $total_estoque)
        $lock = true
      else
        $lock = false
      end
    elsif @estoque.valida_por.eql?("total_produtos")
      $total_estoque = @estoque.valor_total_produto.to_f
      if ($total_produtos < $total_estoque) or ($total_produtos > $total_estoque)
        $lock = true
      else
        $lock = false
      end
    end
    respond_to &:js
  end

  private
    def _start_
      @estoque = user.estoques_movimentos.build(resource_params)
    end

    def _successfully_created_
      @estoque.save
    end

    def _check_transfer_
      if @estoque.tipo_movimentacao.eql?("Transferência")
        @estoque.add_transferencia_tipo=resource_params[:transferencia_tipo]
        @estoque.save
      end
    end

    def _reload_if_item_parcelas_
      if !@estoque.tipo_movimentacao.eql?("Transferência")
        @estoque_produtos = @estoque.estoque_produtos
        unless @estoque_produtos.empty?
          @estoque_produtos.each do |ep|
            Estoque::EstoqueProduto.build_parcelamento_from_source(ep, @estoque.parcelas)
          end
        end
      else
        @estoque_transferencias = @estoque.estoque_transferencias
        unless @estoque_transferencias.empty?
          @estoque_transferencias.each do |et|
            Estoque::EstoqueTransferencia.build_parcelamento_from_source(et, @estoque.parcelas)
          end
        end
      end
    end

    def _successfully_updated_
      @estoque.update(resource_params)
      session[:qtParcelas]= @estoque.parcelas
    end

    def find_estoque
      @id = check_params
      @estoque = Estoque::EstoqueMovimento.find_by(id: @id.call(params[:id], params[:estoque_movimentaco_id]))
    end

    def resource_params
      params.require(:estoque_estoque_movimento).permit(:id,
                                                        :tipo_movimentacao,
                                                        :fornecedor_id,
                                                        :destinatario_tomador_id,
                                                        :user_id,
                                                        :nota_fiscal_entrada,
                                                        :numero_pedido,
                                                        :recibo,
                                                        :cupom_fiscal,
                                                        :numero_da_os,
                                                        :nota_fiscal_saida,
                                                        :data_entrada,
                                                        :data_vencimento_entrada,
                                                        :data_vencimento_saida,
                                                        :data_saida,
                                                        :data_devolucao,
                                                        :data_transferencia,
                                                        :justificativa_devolucao,
                                                        :transferencia_tipo,
                                                        :total_estoque,
                                                        :parcelas,
                                                        :periodo,
                                                        :valor_total_produto,
                                                        :acrescimo,
                                                        :boleto,
                                                        :frete,
                                                        :desconto,
                                                        :observacoes,
                                                        :valida_por,
                                                        :pronto_pagamento)
    end
end

app/controllers/estoques/estoque_produtos_controller.rb
# -*- coding: utf-8 -*-
class Estoques::EstoqueProdutosController < BrantController
  include CurrentItem
  before_action :find_estoque
  respond_to :html

  def new
    verifica_itens_adicionados
    @estoque_produto = @estoque.estoque_produtos.build
    @produto = @estoque.produtos.build
    @produto.categorias.build
    session[:qtParcelas]= @estoque.parcelas
  end

  def create
    if resource_params[:id].eql?("")
      verifica_itens_adicionados
      @estoque_produto = @item.add_produto_to_estoque(resource_params)
      @estoque_produto.verify_last_stock
      @estoque_produto.add_or_remove_through_stock_moviment
      if @estoque_produto.save
        @estoque_produto.save_product_at_provider_if_not_exists
        @estoque_produto_parcelamentos = Estoque::EstoqueProduto.build_parcelamento_from_source(@estoque_produto, session[:qtParcelas])
        if @estoque_produto_parcelamentos 
          flash[:notice]=t("flash.actions.#{__method__}.success", resource_name: "Produto")
          redirect_to new_estoques_estoque_movimentaco_estoque_produto_path(@estoque)
        end
      else
        flash[:error]=t("flash.actions.#{__method__}.alert", resource_name: "Produto")
        @item = Item.find(session[:item_id])
        render :new
      end
    else
      update
    end
  end

  def update
    @estoque_produto = @estoque.estoque_produtos.find(resource_params[:id])
    @estoque_produto.verify_changes_on_main_fields(resource_params)
    @estoque_produto.simula_valor_total_de_produtos(resource_params[:valor_produto])

    if @estoque_produto.save
      @estoque_produto_parcelamentos = Estoque::EstoqueProduto.build_parcelamento_from_source(@estoque_produto, session[:qtParcelas])
      if @estoque_produto_parcelamentos
        flash[:notice] = t("flash.actions.#{__method__}.success", resource_name: "Produto")
        redirect_to new_estoques_estoque_movimentaco_estoque_produto_path(@estoque)
      end
    else
      flash[:error] = t("flash.actions.#{__method__}.alert", resource_name: "Produto")
      render 'new'
    end
  end

  def destroy
    @estoque_produto = Estoque::EstoqueProduto.find(params[:id])
    @estoque = Estoque::EstoqueMovimento.find(params[:estoque_movimentaco_id])
    @deleted_id =@estoque_produto.id
    
    if @estoque_produto.destroy
      @confirmed = true
    else
      @confirmed = false
    end
  end


  private
    def verifica_itens_adicionados
      @estoque_produto = @estoque.estoque_produtos.last
      if !@estoque_produto.nil?
        @item = @estoque_produto.item
        session[:item_id] = @item.id
      elsif session[:item_id] != nil
        @item = Item.find(session[:item_id])
      else
        @item = Item.create
        session[:item_id] = @item.id
      end
    end

    def find_estoque
      @estoque = Estoque::EstoqueMovimento.find(params[:estoque_movimentaco_id])
    end

    def resource_params
      params.require(:estoque_estoque_produto).permit(:id,
                                                      :produto_id,
                                                      :estoque_movimento_id,
                                                      :obra_id,
                                                      :comodo_id,
                                                      :item_obra_id,
                                                      :sub_item_obra_id,
                                                      :quantidade_movimento,
                                                      :quantidade_anterior,
                                                      :quantidade_atual,
                                                      :valor_produto,
                                                      :valor_total,
                                                      :observacoes)
    end
end

app/views/estoques/estoque_parcelamentos/_parcelamento_in_field_form.html.haml
=form_for @estoque_parcelamento, url: estoques_update_estoque_parcelamento_path, method: :put, html: {style: "display: inline-block"} do |f|
  =f.text_field :valor_parcela, class: "form-control in_place_editing"
  = button_tag(type: "submit", class: 'btn btn-success btn-circle', title: "Alterar valor", style: "margin-right: 5px") do
    %i.fa.fa-check{"aria-hidden" => "true"}
  = button_tag(type: "submit", class: 'btn btn-danger btn-circle', title: "Cancelar", style: "") do
    %i.fa.fa-times{"aria-hidden" => "true"}

app/views/estoques/estoque_parcelamentos/change.js.erb
$("#quotation_change_link_<%= @estoque_parcelamento.id %>").remove()
$(".parcelamento_id_<%= @estoque_parcelamento.id %>").html("<%=j render 'estoques/estoque_parcelamentos/parcelamento_in_field_form', {estoque_parcelamento: @estoque_parcelamento} %>")

app/views/estoques/estoque_parcelamentos/editar_parcelamentos.html.haml
%section{id: "new_parcelamento"}
  .container
    .row-fluid
      %h1.page_header{style: "border-bottom: #AEAEAE 0.5px solid"}
        =t('helpers.titles.edit', model: "Parcelamento")
  .container
    .well
      #exTab3.container-fluid
        %ul.nav.nav-pills
          %li
            %a{"data-toggle" => "tab", :href => "#tab_moviment"}=t('estoques.links.tab_moviment')
          %li.active
            %a{"data-toggle" => "tab", :href => "#tab_parcelamento"}=t('estoques.links.tab_parcelamento')
        .tab-content.clearfix
          #tab_moviment.tab-pane.fade.in
            =render 'estoques/estoque_movimentacoes/estoque/movimento'
          #tab_parcelamento.tab-pane.fade.in.active
            %br
            .col-md-6
              .row
                .col-md-12
                  -if @estoque_produto
                    =render 'estoques/estoque_parcelamentos/produto', { item: @estoque_produto }
                  -if @estoque_transferencia
                    =render 'estoques/estoque_parcelamentos/produto', { item: @estoque_transferencia }
            .col-md-6
              .row
                .col-md-12
                  .panel.panel-default
                    .panel-heading
                      %h4.center
                        %strong=t('helpers.labels.parcelas')
                      =simple_form_for @estoque_parcelamento, url: estoques_estoque_estoque_parcelamento_find_and_create_portions_path, method: :post do |f|
                        .row
                          =f.input :estoque_movimento_id, as: :hidden, input_html: { value: @estoque.id }
                          -if @estoque_produto
                            =f.input :estoque_produto_id, as: :hidden, input_html: { value: @estoque_produto.id }
                          -if @estoque_transferencia
                            =f.input :estoque_transferencia_id, as: :hidden, input_html: { value: @estoque_transferencia.id }
                        .row
                          .col-xs-12.col-sm-8.col-md-6.col-lg-6
                            %label=t('helpers.labels.parcelas')
                            .input-group
                              %span.input-group-addon
                                %i.fa.fa-pie-chart
                              =f.input :parcelas, label: false ,as: :integer, input_html: { min: 1, value: 1 }
                          .col-xs-12.col-sm-8.col-md-6.col-lg-6
                            %label=t('helpers.labels.valor')
                            -if @estoque_produto
                              .input-group
                                %span.input-group-addon
                                  %b R
                                  %i.fa.fa-dollar
                                =f.input :valor_parcela, as: :string, label: false, input_html: { class: "campo_dinheiro", value: @estoque_produto.valor_total.to_money }
                            -if @estoque_transferencia
                              .input-group
                                %span.input-group-addon
                                  %b R
                                  %i.fa.fa-dollar
                                =f.input :valor_parcela, as: :string, label: false, input_html: { class: "campo_dinheiro", value: @estoque_transferencia.valor_total.to_money }
                        .row
                          %br/
                          .col-md-12=render 'estoques/componentes/progress_bar'
                        .row
                          .pull-left
                            .col-xs-12.col-sm-8.col-md-5.col-lg-5
                              = button_tag(type: "submit", class: 'btn btn-success', title: "Adicionar Produto no Estoque", style: "margin-top: 23px;") do
                                %i.fa.fa-check{"aria-hidden" => "true"}
                                =t('helpers.links.end')
                          .pull-right
                            .col-xs-12.col-sm-8.col-md-5.col-lg-5
                              -if @estoque_produto
                                =link_to new_estoques_estoque_movimentaco_estoque_produto_path(@estoque), class: "btn btn-danger", style: "margin-top: 23px;" do
                                  %i.fa.fa-times{"aria-hidden" => "true"}
                                  =t('helpers.links.cancel')
                              -if @estoque_transferencia
                                =link_to new_estoques_estoque_movimentaco_estoque_transferencia_path(@estoque), class: "btn btn-danger", style: "margin-top: 23px;" do
                                  %i.fa.fa-times{"aria-hidden" => "true"}
                                  =t('helpers.links.cancel')


= javascript_include_tag "https://code.jquery.com/jquery-3.2.1.js"
= javascript_include_tag "brant/estoques/parcelamento"

app/views/estoques/estoque_parcelamentos/index.html.haml
- produto = @estoque_parcelamentos.last.estoque_produto.produto.descricao if !@estoque_parcelamentos.last.estoque_produto.nil?
- produto = @estoque_parcelamentos.last.estoque_transferencia.produto.descricao if !@estoque_parcelamentos.last.estoque_transferencia.nil?
%section{id: "exibindo_parcelamentos"}
  .container
    .row-fluid
      %span.breadcrumb-item.active Você está em
      %h4.page_header{style: "border-bottom: #AEAEAE 0.5px solid"}
        .btn-group.pull-right
          =link_to estoques_estoque_movimentaco_path(@estoque), class: "btn btn-success", title: "Voltar para o Estoque" do
            %i.fas.fa-lock{"aria-hidden" => "true", style: "color: gold"}
            =t('helpers.links.finish_release')
          = link_to edit_estoques_estoque_movimentaco_path(@estoque), class: "btn btn-primary" do
            %i{class: "fa fa-pencil-square-o",  "aria-hidden" => "true"}
            =t('helpers.links.change_data_moviment')
          =link_to new_estoques_estoque_movimentaco_estoque_produto_path(@estoque), class: "btn btn-default", title: "Voltar para o Estoque" do
            %i{class: "fa fa-plus", "aria-hidden" => "true", style: "color: tomato" }
            =t('helpers.links.add_produto')
        %ol.arrows
          %li
            %a{:href => "#"}="Estoque Nº #{@estoque.id}"
          %li
            %a{:href => "#"}="Produto - #{produto}"
          %li
            %a{:href => "#"} Parcelamentos
  .container
    .well
      #exTab3.container-fluid
        %ul.nav.nav-pills
          %li
            %a{"data-toggle" => "tab", :href => "#tab_moviment"}=t('estoques.links.tab_moviment')
          %li.active
            %a{"data-toggle" => "tab", :href => "#tab_parcelamento"}=t('estoques.links.tab_parcelamento')
        .tab-content.clearfix
          #tab_moviment.tab-pane.fade.in
            =render 'estoques/estoque_movimentacoes/estoque/movimento'
          #tab_parcelamento.tab-pane.fade.in.active
            %br
            .panel.panel-default
              .panel-heading
                .page-header
                %table.table.table-condensed.table-hover.table-striped
                  %caption
                    %strong=t('helpers.labels.objeto_em_destaque', model: "Produto")
                  %thead
                    %tr
                      %th=t('produtos.helpers.nome')
                      %th=t('helpers.labels.obra')
                      %th.center=t('produtos.helpers.quantidade')
                      %th.center=t('produtos.helpers.valor')
                      %th
                        .pull-right=t('produtos.helpers.valor_total')
                  %tbody.estoque_produto
                    - if !@estoque_parcelamentos.last.estoque_produto.nil?
                      =render 'estoques/estoque_parcelamentos/estoque_parcelamento_item', { item: @estoque_parcelamentos.last.estoque_produto}
                    - if !@estoque_parcelamentos.last.estoque_transferencia.nil?
                      =render 'estoques/estoque_parcelamentos/estoque_parcelamento_item', { item: @estoque_parcelamentos.last.estoque_transferencia}
                %caption
                  %b=t('helpers.labels.total_parcelas', total: @estoque_parcelamentos.count)
            %br/
            %section#parcelas_produtos
              .panel.panel-default
                .panel-heading
                  %label{id: "click", style: "color: #F43737"}
                    =t("helpers.labels.click")
                  %label{style: "color: #0B1200"}
                    =t('helpers.labels.clique_no_valor')
                  ="-"
                  - unless @estoque_parcelamentos.last.estoque_produto.nil?
                    =link_to "#", id: "btn_resetar_parcelas_estoque_produto", class: "btn btn-warning", data: {estoque_movimento_id: @estoque.id, estoque_produto_id: @estoque_parcelamentos.last.estoque_produto.id, parcelas: @estoque_parcelamentos.last.estoque_movimento.parcelas} do
                      %span.fa.fa-refresh{"aria-hidden" => "true"}
                      =t('helpers.labels.update_parcelas')
                  - unless @estoque_parcelamentos.last.estoque_transferencia.nil?
                    =link_to "#", id: "btn_resetar_parcelas_estoque_transferencia", class: "btn btn-warning", data: {estoque_movimento_id: @estoque.id, estoque_transferencia_id: @estoque_parcelamentos.last.estoque_transferencia.id, parcelas: @estoque_parcelamentos.last.estoque_movimento.parcelas} do
                      %span.fa.fa-refresh{"aria-hidden" => "true"}
                      =t('helpers.labels.update_parcelas')
                  .col-md-4.pull-right{style: "margin-top: 1%"}=render 'estoques/componentes/progress_bar'
                .panel-body
                  %section#best_in_place_parcelamento
                    .row
                      - parcela = 1
                      -@estoque_parcelamentos.each do |parcelamento|
                        .col-md-4.col-lg-3
                          .w3-main
                            .card.w3-card-4.w3-section
                              %header.w3-container.w3-light-grey
                                %h5.center
                                  %label.badge{style: "color: #C4FF30"}="#{parcela}x"
                                  =t('helpers.labels.payday_on')
                                  =l parcelamento.data_vencimento
                              .w3-container
                              .w3-button.w3-block.w3-black.w3-hover-black
                                -if !parcelamento.bloqueado?
                                  =render 'estoques/estoque_parcelamentos/best_in_place_field', {parcelamento: parcelamento}
                                - else
                                  #unlock_value_span_area{style: "display: inline"}
                                    %span.w3-text-pink
                                      =number_to_currency parcelamento.valor
                                      =link_to(unlock_value_estoques_estoque_movimentaco_estoque_parcelamento_path(parcelamento.estoque_movimento_id, parcelamento), class: "popover_link", id: "btn_unlock_quotation", :"data-toggle"=> "popover", :"data-content" => t('pages.helpers.title-content.unlock_value'), :"data-placement"=>"right", :"data-trigger"=>"hover") do
                                        %i.btn_unlock_icon.fa.fa-lock
                        - parcela += 1
                      .clearfix

%section#associations
  %input{type: "hidden", id: "estoque_movimento_id", value: @estoque_parcelamentos.last.estoque_movimento_id, readonly: true}
  %input{type: "hidden", id: "estoque_produto_id", value: params[:estoque_produto_id], readonly: true}
  %input{type: "hidden", id: "estoque_transferencia_id", value: params[:estoque_transferencia_id], readonly: true}


%section#warning-message
  =render 'estoques/componentes/page_lock'

= javascript_include_tag "https://code.jquery.com/jquery-3.2.1.js"
= javascript_include_tag "brant/estoques/parcelamento"